INSERT INTO `pinglei` VALUES ('水果礼篮', '水果礼篮');
INSERT INTO `pinglei` VALUES (' 充值券卡', ' 充值券卡          ');
INSERT INTO `pinglei` VALUES ('果园周边', '果园周边');
INSERT INTO `pinglei` VALUES ('凤梨', '凤梨');
INSERT INTO `pinglei` VALUES ('苹果', '苹果          ');
INSERT INTO `pinglei` VALUES ('无花果', '无花果');
INSERT INTO `pinglei` VALUES ('牛油果', '牛油果');
INSERT INTO `pinglei` VALUES ('杏子', '杏子');
INSERT INTO `pinglei` VALUES ('组合套餐', '组合套餐');
INSERT INTO `pinglei` VALUES ('水果礼盒', '水果礼盒');
INSERT INTO `pinglei` VALUES ('香蕉', '香蕉');
INSERT INTO `pinglei` VALUES ('火龙果', '火龙果');
INSERT INTO `pinglei` VALUES ('枣', '枣');
INSERT INTO `pinglei` VALUES ('瓜类', '瓜类');
INSERT INTO `pinglei` VALUES ('桔柑类', '桔柑类');
INSERT INTO `pinglei` VALUES ('龙眼', '龙眼');
INSERT INTO `pinglei` VALUES ('橙子', '橙子');
INSERT INTO `pinglei` VALUES ('芒果', '芒果');
INSERT INTO `pinglei` VALUES ('石榴 ', ' 石榴 ');
INSERT INTO `pinglei` VALUES ('西梅', '西梅');
INSERT INTO `pinglei` VALUES ('柿子', '柿子');
INSERT INTO `pinglei` VALUES ('樱桃', '樱桃');
INSERT INTO `pinglei` VALUES ('李子', '李子');
INSERT INTO `pinglei` VALUES ('红毛丹', '红毛丹');
INSERT INTO `pinglei` VALUES (' 梨', ' 梨');
INSERT INTO `pinglei` VALUES ('蓝莓', '蓝莓');
INSERT INTO `pinglei` VALUES ('百香果', '百香果');
INSERT INTO `pinglei` VALUES ('奇异果', '奇异果');
INSERT INTO `pinglei` VALUES ('柚子', '柚子');
INSERT INTO `pinglei` VALUES ('榴莲', '榴莲');
INSERT INTO `pinglei` VALUES ('椰子', '椰子');
INSERT INTO `pinglei` VALUES ('柠檬', '柠檬');
INSERT INTO `pinglei` VALUES ('葡萄提子', '葡萄提子');
INSERT INTO `pinglei` VALUES ('葡萄柚', '葡萄柚');
